spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:talentdb}
    username: ${DB_USER:talentdb}
    password: ${DB_PASS:talentdb}

app:
  storage:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    accessKey: ${MINIO_ACCESS_KEY:minioadmin}
    secretKey: ${MINIO_SECRET_KEY:minioadmin}
